### PR TITLE
Skip equal elements from begin and end optimization. Also trivial optimization if { from } and { to } are same objects.

### PR DESCRIPTION
**Pull request by bga**
That optimization reduces `grid` size primary and also hugely reduces run time coz Levenshtein is O(n*m)
Changed only [esm/main.js] and [cjs/main.js] files but not [./index.js] nor [./min.js] coz unfortunately nmp does not work on my Win7 machine and i can not even do { npm install } to download deps and do automatic tests but i tested manually.

### CODE REVIEW

**Comment by WebReflection** [comment]
Thanks for the PR, too bad npm doesn't work in your machine ... time to switch to Linux ?

Anyway, this is the list of things I'd like to see before moving forward:

  * you need to change **only** the esm/index.js which is the source of truth
  * you need to squash all changes so that I have one single commit to go through and review changes
  * you need to keep code-coverage to 100% otherwise it won't get merged

Thank You!

**Comment by bga** [comment]
now this PR satisfies rules

**Comment by WebReflection** [comment]
mind dropping changes from cjs/main.js ?

**Comment by bga** [comment]
Yes. cjs/main.js is clean

**Comment by WebReflection** [comment]
I still see it?
https://github.com/WebReflection/majinbuu/pull/1/commits/01c2bbeb7df8112d38bac63d61fb95cf17c56131#diff-b6c71a7d4914f17f2bdd34e7fead0b42

**Pull request closed without merging**
